apiVersion: v1
kind: Secret
metadata:
  name: isabella-jdr-secrets
  labels:
    app: isabella-jdr
type: Opaque
stringData:
  db-url: "jdbc:mysql://mysql:3306/isabella_jdr"
  db-username: "REPLACE_ME"
  db-password: "REPLACE_ME"
  oidc-issuer: "https://REPLACE_ME/.well-known/openid-configuration"
  oidc-audience: "isabella-jdr"
